### PR TITLE
Fix infinite loop in Suspense error handling on the server

### LINKED ISSUE #1648: Maximum call stack size exceeded in Suspense error handling on the server
### Describe the bug

If an accessed resource throws an error during SSR, Suspense will go into an infinite loop trying to handle it.
This issue only exists in versions `>=1.6.13` so most likely this is a regression caused by this commit: 60f8624db81e5491bdd3f4b69870899976212941

I think I know where the problem is, so I'll try to make a PR

image

### Your Example Website or App

https://stackblitz.com/edit/server-suspense-infinite-loop?file=index.ts

### Steps to Reproduce the Bug or Issue

1. `pnpm i` to install deps
2. `pnpm dev` to run the server script
3. look at the error message

### Expected behavior

The error should be able to be handled by an error boundary

### PR DESCRIPTION
**Pull request by thetarnav**
## Summary

Fixes #1648 

Suspense was attaching it's `onError` not to the `o` new owner it created, but to the current `Owner`, which ends up being the parent of `o`. So when it tries to pass the error to the parent with `runWithOwner`, it's actually passing it to itself creating an infinite loop.

## How did you test this change?

I see there are no server tests for solid-js at the moment. But patching solid-js locally has solved this issue for me.
I'm not sure if I should maybe try adding one using `// @jest-environment node` comment to force node env with jest?
Maybe after #1609 gets merged this could be improved.

### CODE REVIEW

File: packages/solid/src/server/rendering.ts [hunk 1]
```diff
@@ -552,7 +552,6 @@ export function SuspenseList(props: {
 
 export function Suspense(props: { fallback?: string; children: string }) {
   let done: undefined | ((html?: string, error?: any) => boolean);
-  let clean: any;
```
Comment (thetarnav) [inline packages/solid/src/server/rendering.ts:555]: `clean` wasn't being used anywhere anymore. maybe that's a mistake? not sure what it did

File: packages/solid/src/server/rendering.ts [hunk 2]
```diff
@@ -569,8 +568,8 @@ export function Suspense(props: { fallback?: string; children: string }) {
     });
   function runSuspense() {
     setHydrateContext({ ...ctx, count: 0 });
-    o && cleanNode(o);
```
Comment (thetarnav) [inline packages/solid/src/server/rendering.ts:572]: `o` is always present. before 1.6.13 `clean` was checked here

Comment (ryansolid) [reply packages/solid/src/server/rendering.ts:572]: Are we sure we can just remove it? I hoisted it up for sure and that caused the issue, but it was always there. I guess I can retest the original React Query scenario.

Comment (thetarnav) [reply packages/solid/src/server/rendering.ts:572]: pre `1.6.13` the current `Owner` would get assigned as `o` so it could be `null`, now we are always a new owner so the condition is pointless.

Comment (thetarnav) [reply packages/solid/src/server/rendering.ts:572]: Also, github is showing the preview a bit weirdly. I didn't remove `cleanNode(o)`, just `o &&`

Comment (ryansolid) [reply packages/solid/src/server/rendering.ts:572]: Oh I get it. Yeah I was looking at the wrong part. I guess the trickiest part is I change this mechanism completely in 1.7. It's going to be a bit interesting to figure out how to merge this back into next. It looks like I need to do another 1.6 release given the stuff I've broken though so I will go with this for now.
