### PR TITLE
fix(typescript): `Setter<T>` being assignable to any `Setter`

### LINKED ISSUE #1818: `Setter<bigint>` should not be assignable to `Setter<number>` and vice versa
### Describe the bug

`Setter<number>` is assignable to `Setter<bigint>`. `Accessor<number>` is not assignable to `Accessor<bigint>`.

The same goes for the opposite case: `Setter<bigint>` is assignable to `Setter<number>`. `Accessor<bigint>` is not assignable to `Accessor<number>`.

The type error should be there for `Setter` too, just like it is for `Accessor`.

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-6dfgbm?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

- Open stackblitz as given above.
- Once packages are installed, you will see the type error for `Accessor` but not for `Setter`.

### Expected behavior

`Setter<number>` should not be assignable to `Setter<bigint>`.

### Screenshots or Videos

_No response_

### Platform

- OS: macOS
- Browser: Brave (Chrome)
- Version: see below
```json
  "devDependencies": {
    "typescript": "^5.1.3",
    "vite": "^4.3.9",
    "vite-plugin-solid": "^2.7.0"
  },
  "dependencies": {
    "solid-js": "^1.7.6"
  }
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by otonashixav**
## Summary

For some reason this fixes #1818. I assume it's because internally typescript does something slightly different but honestly have no clue why this works.

### Further Changes

Switched to using variance annotations, and to have that work changed the type to be a single overloaded function. With variance annotations different `Setter`s will not be mutually assignable; some of the edge cases seem to only be solved by it. The parameterless case is handled somewhat awkwardly, however. As a result, generically typed Setters must now non-null assert their parameter, i.e.

```diff
function myCustomSignal<T>(v: T) {
  const [get, set] = createSignal<T>();
-   const mySetter: Setter<T | undefined> = (v?) => set(v);
+   const mySetter: Setter<T | undefined> = (v?) => set(v!);

  const [get, set] = createSignal<T>(v);
-   const mySetter: Setter<T> = (v?) => set(v);
+   const mySetter: Setter<T> = (v?) => set(v!);
}
```

## How did you test this change?

Added a test case.

### CODE REVIEW

**Comment by otonashixav** [comment]
This still isn't a complete solution: https://tsplay.dev/wga0bm

I pushed it for now with the failing tests.

**Comment by ryansolid** [comment]
Thank you

File: packages/solid/src/reactive/signal.ts [hunk 1]
```diff
@@ -174,10 +174,14 @@ export function createRoot<T>(fn: RootFunction<T>, detachedOwner?: typeof Owner)
 
 export type Accessor<T> = () => T;
 
-export type Setter<T> = (undefined extends T ? () => undefined : {}) &
-  (<U extends T>(value: (prev: T) => U) => U) &
-  (<U extends T>(value: Exclude<U, Function>) => U) &
-  (<U extends T>(value: Exclude<U, Function> | ((prev: T) => U)) => U);
+export type Setter<in out T> = {
```
Comment (so1ve) [inline packages/solid/src/reactive/signal.ts:177]: @otonashixav Hi, sorry for disturbing. Could you please tell me what this syntax is?
